# Generated by Django 4.1.2 on 2022-10-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(default='', max_length=200)),
                ('emp_id', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
